name: CI

on:
  push:

jobs:
  verification:
    name: verification
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install dependencies
      run: npm ci
# step pour les linters etc -> pas détaillée ici

  cypress-test:
    name: cypress test
    needs: verification
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install dependencies
      run: npm ci
    - name: Run tests
      run: npm run cy:run
    - name: Upload Screenshots reports
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: cypress-screenshots
        path: cypress/screenshots
    - name: Upload Video reports
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: videos
        path: cypress/videos
